"""Derive the gemm cases and their reference from the real-v6e measurements.

The measurement tree is the source of truth: a case exists because silicon ran
that exact (M, K, N), and its reference is that run's device time.  Rewrites
`ops/gemm.py` and `ref_v6e.csv`; nothing else generates either file.
"""

import argparse
import csv
import glob
import os
import re
import statistics

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_TREE = "/workspace/tpuv6e_validation"

#: v6e config clock -- cycles are the simulator's unit, so its own clock converts.
#: configs/systolic_ws_256x256_c1_simple_noc_tpuv6e.yml:core_freq_mhz
CORE_FREQ_MHZ = 3502

#: Measurements are bfloat16.  The harness pairs them with its float16 runs: the
#: two differ in exponent/mantissa split, not in bytes, and timing reads bytes.
DTYPE = "float16"

#: M values kept per weight shape.  The measured grids run to 87 points, which is
#: a sweep, not a case list; this ladder crosses the knees the array cares about
#: (1 -> the 256-row array height -> weight-streaming saturation) and drops the
#: interpolation filler between them.  The largest measured M is always kept.
LADDER = [1, 32, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768]


def models(tree):
    """MODELS from the sweep harness -- the only place the dims are written down."""
    src = open(os.path.join(tree, "code/harness/tpu_lut_sweep_v2.py")).read()
    ns = {}
    exec(re.search(r"^MODELS = \{.*?^\}", src, re.S | re.M).group(0), ns)
    return ns["MODELS"]


def weight_shape(m, op):
    """(K, N) of the one weight this op multiplies, or None if it is not one GEMM."""
    h, inter, enc = m["h"], m["inter"], m["type"] == "enc"
    return {"qkv": (h, (m["hq"] + 2 * m["hkv"]) * m["d"]),
            "out_proj": (m["hq"] * m["d"], h),
            "ffn_g1": (h, inter if enc else 2 * inter),
            "ffn_g2": (inter, h),
            "lm_head": (h, m["vocab"])}.get(op)


def collect(tree):
    """(M, K, N) -> [(model, op, latency_ns)] over every measured linear GEMM."""
    MODELS = models(tree)
    out = {}
    for path in sorted(glob.glob(os.path.join(tree, "data/linear_gemm/*.csv"))):
        model, op = os.path.basename(path)[:-4].split("__")
        shape = weight_shape(MODELS[model], op)
        if shape is None:          # ffn / ffn_gemm_only are two GEMMs in one program
            continue
        for row in csv.DictReader(open(path)):
            key = (int(row["tokens"]),) + shape
            out.setdefault(key, []).append((model, op, float(row["latency_ns"])))
    return out


def select(points):
    """The ladder rows, plus the largest M measured for each weight shape."""
    by_shape = {}
    for M, K, N in points:
        by_shape.setdefault((K, N), []).append(M)
    keep = set()
    for shape, ms in by_shape.items():
        wanted = {m for m in ms if m in LADDER} | {max(ms)}
        keep |= {(m,) + shape for m in wanted}
    return sorted(keep, key=lambda k: (k[1], k[2], k[0]))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tree", default=DEFAULT_TREE, help="tpuv6e_validation root")
    ap.add_argument("--dry-run", action="store_true", help="count only, write nothing")
    args = ap.parse_args()

    points = collect(args.tree)
    chosen = select(points)
    print(f"측정 고유 (M,K,N) {len(points)} -> 케이스 {len(chosen)}  "
          f"(weight shape {len({k[1:] for k in points})}개)")
    if args.dry_run:
        return

    cases, ref = [], []
    for key in chosen:
        M, K, N = key
        rows = points[key]
        ns = statistics.median(r[2] for r in rows)
        who = ",".join(sorted({f"{r[0]}/{r[1]}" for r in rows}))
        spread = (max(r[2] for r in rows) - min(r[2] for r in rows)) / ns if len(rows) > 1 else 0.0
        note = f"M={M} 토큰. {'같은 shape을 잰 단위 %d개, 편차 %.1f%%' % (len(rows), spread * 100) if len(rows) > 1 else ''}"
        cases.append((f"gemm_{M}x{K}x{N}", (M, K, N), "v6e", "exact", who, note.strip()))
        ref.append({"workload": f"gemm_{M}x{K}x{N}", "dtype": DTYPE,
                    "cycles": round(ns * 1e-9 * CORE_FREQ_MHZ * 1e6),
                    "latency_ns": round(ns), "source": who, "n_units": len(rows)})

    with open(os.path.join(HERE, "ops/gemm.py"), "w") as f:
        f.write('"""gemm — timing-mode validation cases, derived from real v6e runs.\n\n'
                'size = (M, K, N).  GENERATED by gen_v6e_cases.py -- do not hand-edit.\n'
                'Every case is a shape silicon ran; ref_v6e.csv carries its device time.\n'
                '"""\n\nPARAMS = "M, K, N"\n\n'
                '#: (name, size, origin, census, source, note).\n'
                '#: origin  v6e (a real TPU v6e measured this exact shape)\n'
                '#: census  exact (the measurement ran it; nothing here is interpolated)\n'
                'CASES = [\n')
        for name, size, origin, census, source, note in cases:
            f.write(f'    ("{name}", {size}, "{origin}", "{census}", "{source}", "{note}"),\n')
        f.write(']\n')

    with open(os.path.join(HERE, "ref_v6e.csv"), "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(ref[0]))
        w.writeheader()
        w.writerows(ref)

    print(f"ops/gemm.py  {len(cases)} cases")
    print(f"ref_v6e.csv  {len(ref)} rows  ({DTYPE}, {CORE_FREQ_MHZ} MHz)")


if __name__ == "__main__":
    main()
