"""lower_to_emitc pass (C4): skeleton+API MLIR -> EmitC -> C++ -> trace `.so`.

Second stage of the C++ trace pipeline (docs/design/togsim_cpp_trace.md, sec
5-7). Takes the skeleton+API module from `build_skeleton` (loop nest +
`togsim.*` ops) and produces an EmitC module whose single entry function

    extern "C" void togsim_kernel(EmitCtx* ctx, int64_t* shape_args, int32_t n)

mirrors the loop skeleton, with every `togsim.*` op as an `emitc.call_opaque`
to the matching `togsim_runtime.h` free function (`togsim_ops.EMITC_CALLEE`).
`mlir-translate --mlir-to-cpp` renders it to C++, compiled to a `.so` that
exports `togsim_kernel` and leaves `togsim_dma/wait/compute/signal` undefined for
the TOGSim loader to resolve at `dlopen`.

How the lowering is done -- it drives the *upstream* EmitC conversion passes and
adds only the glue they cannot do:

  1. (python) Rewrite the unregistered `togsim.*` ops to `emitc.call_opaque`.
     Unregistered ops have no registered conversion patterns, so this must be a
     custom rewrite (design sec 8). Also rewrite the kernel's signature to the
     ABI form (drop the memref tensor args -- the trace producer never touches
     tensor data; base addresses are deferred to P3) and drop the aux
     globals / wrapper func.
  2. (upstream passes, in-process PassManager)
        func.func(lower-affine) -> convert-scf-to-emitc
        -> convert-arith-to-emitc -> convert-func-to-emitc
     This is the EmitC infrastructure: it lowers the affine/scf loop nest to
     `emitc.for`, the index/arith (loop bounds, and in P3 the address
     arithmetic) to EmitC, and the func to `emitc.func`.
  3. (python) Two small fixups the passes leave behind in this LLVM 20 build:
       * `convert-scf-to-emitc` emits `emitc.for` with `index`-typed bounds, so
         `convert-arith-to-emitc` (which makes constants `!emitc.size_t`) leaves
         `builtin.unrealized_conversion_cast` on the bounds that nothing folds
         and `mlir-to-cpp` cannot print (design sec 8 "EmitC coverage" risk).
         `_fold_for_bound_casts` rewrites those casts away.
       * add the `extern "C"` specifier so `dlsym` finds the entry unmangled.

Requires the MLIR Python bindings (incl. `mlir.passmanager`); the .cpp/.so
steps additionally require `mlir-translate` (TORCHSIM_LLVM_PATH) and a host C++
compiler.
"""

import os
import re
import subprocess

from mlir.passmanager import PassManager

from . import togsim_ops as ts
from ._mlir_util import walk_ops, i32, i64, attr_int, attr_i64_array
from .build_tog import ir, _find_kernel

#: emitted entry symbol (== ts.ENTRY_SYMBOL == "togsim_kernel").
ENTRY = ts.ENTRY_SYMBOL

#: EmitC type of the opaque EmitCtx* threaded through every call.
CTX_TYPE = '!emitc.ptr<!emitc.opaque<"EmitCtx">>'

#: upstream EmitC conversion pipeline (the infrastructure this pass drives).
_PIPELINE = ("builtin.module("
             "convert-vector-to-scf{full-unroll=true},"
             "func.func(lower-affine),"
             "func.func(lower-vector-multi-reduction),"
             "convert-scf-to-emitc,"
             "convert-arith-to-emitc,"
             "convert-func-to-emitc)")

#: includes every generated trace.cpp needs.
_INCLUDES = (
    "#include <cstddef>\n"
    "#include <cstdint>\n"
    "using std::size_t;\n"
    '#include "togsim_runtime.h"\n'
)


def _trace_banner(include_dir):
    """Self-documenting header for a generated trace.cpp: the ABI version (the
    TOGSIM_ABI_VERSION #define) and the call-format banner, both READ FROM
    togsim_runtime.h so they never drift when the ABI changes. Falls back to a
    bare banner if the header is unreadable."""
    head = "// GENERATED by PyTorchSim -- TOGSim trace producer. DO NOT EDIT.\n"
    try:
        text = open(os.path.join(include_dir, "togsim_runtime.h")).read()
    except OSError:
        return head
    ver = re.search(r"#define\s+TOGSIM_ABI_VERSION\s+(\d+)", text)
    blk = re.search(r"// --- BEGIN trace-producer call formats[^\n]*\n(.*?)"
                    r"// --- END trace-producer call formats[^\n]*\n", text, re.S)
    head = ("// GENERATED by PyTorchSim -- TOGSim trace producer (ABI v%s). DO NOT EDIT.\n"
            % (ver.group(1) if ver else "?"))
    return head + (blk.group(1) if blk else "")


# ---------------------------------------------------------------------------
# attribute builders / readers
# ---------------------------------------------------------------------------
def _idx(v):
    return ir.IntegerAttr.get(ir.IndexType.get(), int(v))


def _opaque(ctx, text):
    return ir.Attribute.parse('#emitc.opaque<"%s">' % text, ctx)


def _arr(ctx, vals):
    """A C compound-literal `(const int64_t[]){...}` arg, or `nullptr` if empty
    (the call site decays it to a `const int64_t*`)."""
    vals = list(vals)
    if not vals:
        return _opaque(ctx, "nullptr")
    return _opaque(ctx, "(const int64_t[]){%s}" % ", ".join(str(int(v)) for v in vals))


def _attr_bool(op, key):
    return 1 if ir.BoolAttr(op.operation.attributes[key]).value else 0


# ---------------------------------------------------------------------------
# step 1: rewrite signature + togsim.* ops (the unregistered-op glue)
# ---------------------------------------------------------------------------
def _strip_aux(module, keep=None):
    """Erase memref.global decls and every func except the kernel.

    `keep` is the kernel op: its name is `kernel` only in PyTorchSim's codegen,
    so the caller passes what `_find_kernel` resolved.
    """
    keep_op = keep.operation if keep is not None else None
    victims = []
    for op in module.body.operations:
        name = op.operation.name
        if name == "memref.global":
            victims.append(op)
        elif name == "func.func":
            if keep_op is not None:
                if op.operation != keep_op:
                    victims.append(op)
            elif ir.StringAttr(op.operation.attributes["sym_name"]).value != "kernel":
                victims.append(op)
    for op in victims:
        op.operation.erase()


class WorkItem:
    """A kernel whose body is ONE work-item, plus the grid over it.

    A Triton kernel describes a single program instance; the grid lives outside
    it. The trace producer already splits the same way (design sec 9.3), so only
    the enumeration is missing.

    `parallel_args` are the argument positions holding the program ids
    (triton-shared appends gridX,Y,Z / pidX,Y,Z after the user scalars); `grid`
    their extents. Both outermost-first.

    An extent may be None, meaning "read it from shape_args at run time". Only
    the NUMBER of axes has to be known when the kernel is compiled -- how many
    loops to nest and how many iv[] slots to fill; the trip counts are just
    values, and the producer ABI already takes them
    (togsim_kernel(ctx, shape_args, n)). That is what lets one compiled trace
    serve every shape.
    """

    def __init__(self, parallel_args, grid):
        if len(parallel_args) != len(grid):
            raise ValueError(
                f"parallel_args {parallel_args} and grid {grid} must have the "
                f"same length -- one program-id argument per grid axis")
        self.parallel_args = list(parallel_args)
        self.grid = [None if g is None else int(g) for g in grid]

    @property
    def dynamic_axes(self):
        """Indices into `grid` whose extent arrives at run time."""
        return [i for i, g in enumerate(self.grid) if g is None]


def _materialize_grid_loop(kernel, work_item, ctx):
    """Wrap the body in the grid loop the Triton kernel does not carry:

        func @k(..., %pid: i32) {
          scf.for %p = 0 to G { <body, %pid -> index_cast %p> } {outer_loop}
        }

    Downstream is then unchanged: `_parallel_loop_chain` finds the tagged loop,
    the outliner threads its induction variable through `iv[]`, and the loop left
    behind becomes the dispatch enumeration. `outer_loop` means "independent
    work-item" (sec 9.1) -- exactly a Triton program id.

    MUST run before `_rewrite_signature`, which erases the arguments and first
    asserts none are still used.
    """
    from mlir.dialects import arith, scf

    block = kernel.regions[0].blocks[0]
    idxty = ir.IndexType.get()
    loc = ir.Location.unknown(ctx)

    pid_args = [block.arguments[i] for i in work_item.parallel_args]
    body_ops = [o for o in block.operations
                if o.operation.name not in _LOOP_TERMINATORS]
    terminator = [o for o in block.operations
                  if o.operation.name in _LOOP_TERMINATORS][0]

    # Every bound first, and all of them before the first loop: each is created
    # just before the terminator, so one made after an outer loop would sit
    # BELOW it in the block while an inner loop uses it -- which does not
    # dominate, and the verifier rejects it (only reachable at rank >= 2).
    with ir.InsertionPoint(terminator), loc:
        c0 = arith.ConstantOp(idxty, ir.IntegerAttr.get(idxty, 0)).result
        c1 = arith.ConstantOp(idxty, ir.IntegerAttr.get(idxty, 1)).result
        # A runtime extent still needs SOMETHING here: shape_args does not exist
        # until _rewrite_signature adds it. The placeholder is replaced by
        # _bind_runtime_bounds once it does.
        ubs = [arith.ConstantOp(idxty, ir.IntegerAttr.get(idxty, e or 1)).result
               for e in work_item.grid]

    loops, inner = [], None
    for ub in ubs:
        # Nest inside the previous loop, BEFORE its yield: InsertionPoint on a
        # block appends, and an scf.for body is already terminated.
        ip = ir.InsertionPoint(terminator) if inner is None \
            else ir.InsertionPoint.at_block_terminator(inner.body)
        with ip, loc:
            loop = scf.ForOp(c0, ub, c1)
        # ForOp leaves the body empty here; scf.for needs a terminator, and
        # _outline_work_item inserts before it.
        if len(loop.body.operations) == 0:
            with ir.InsertionPoint(loop.body), loc:
                scf.YieldOp([])
        loop.operation.attributes["outer_loop"] = ir.BoolAttr.get(True)
        loops.append(loop)
        inner = loop

    # Move the tile body inside the innermost loop, ahead of its yield.
    inner_block = inner.body
    inner_term = inner_block.operations[len(inner_block.operations) - 1]
    for op in body_ops:
        op.operation.move_before(inner_term)

    # Program ids are i32, induction variables index: cast once, at the top.
    with ir.InsertionPoint(inner_block.operations[0]), loc:
        casts = []
        for loop, pid in zip(loops, pid_args):
            iv = loop.body.arguments[0]
            casts.append(arith.IndexCastOp(pid.type, iv).result
                         if pid.type != idxty else iv)

    for pid, new in zip(pid_args, casts):
        _replace_all_uses(pid, new)

    return [(loops[i], ubs[i]) for i in work_item.dynamic_axes]


def _bind_runtime_bounds(pending, shape_arg, ctx):
    """Point each runtime loop bound at `shape_args[k]`.

    Runs AFTER _rewrite_signature, which is what creates the shape_args
    argument. The loops stay in the entry function (the outliner moves only
    their bodies), so the read is in scope where the bound is used.
    """
    if not pending:
        return
    from mlir.dialects import arith

    i64 = ir.IntegerType.get_signless(64)
    idxty = ir.IndexType.get()
    loc = ir.Location.unknown(ctx)
    for k, (loop, placeholder) in enumerate(pending):
        with ir.InsertionPoint(placeholder.owner), loc:
            kc = ir.Operation.create(
                "emitc.constant", results=[i64],
                attributes={"value": ir.IntegerAttr.get(i64, k)}).results[0]
            ref = ir.Operation.create(
                "emitc.subscript", results=[_lvalue(i64)],
                operands=[shape_arg, kc]).results[0]
            elem = ir.Operation.create(
                "emitc.load", results=[i64], operands=[ref]).results[0]
            bound = arith.IndexCastOp(idxty, elem).result
        _replace_all_uses(placeholder, bound)
        placeholder.owner.erase()


def _lvalue(ty):
    """`!emitc.lvalue<ty>`, the result an `emitc.subscript` is required to have."""
    return ir.Type.parse(f"!emitc.lvalue<{ty}>", ty.context)


def _replace_all_uses(old, new):
    """The bindings expose no replaceAllUsesWith on a Value."""
    for use in list(old.uses):
        owner = use.owner
        for i in range(len(owner.operands)):
            if owner.operands[i] == old:
                owner.operands[i] = new


def _rewrite_signature(kernel, ctx):
    """Replace @kernel's memref tensor args with the ABI args
    (EmitCtx*, int64_t* shape_args, int32_t n) and rename it to togsim_kernel.
    Returns the ctx Value."""
    block = kernel.regions[0].blocks[0]
    for arg in block.arguments:
        if len(list(arg.uses)) > 0:
            raise ValueError(
                "kernel arg still used after build_skeleton; cannot drop it "
                "(expected the DCE to have removed all tensor-data ops)")
    # erase existing (memref) args high-to-low, then append the ABI args.
    for i in reversed(range(len(block.arguments))):
        block.erase_argument(i)
    ptr = ir.Type.parse(CTX_TYPE, ctx)
    i64ptr = ir.Type.parse("!emitc.ptr<i64>", ctx)
    i32 = ir.IntegerType.get_signless(32)
    loc = ir.Location.unknown(ctx)
    block.add_argument(ptr, loc)
    block.add_argument(i64ptr, loc)
    block.add_argument(i32, loc)
    kernel.operation.attributes["function_type"] = ir.TypeAttr.get(
        ir.FunctionType.get([ptr, i64ptr, i32], []))
    kernel.operation.attributes["sym_name"] = ir.StringAttr.get(ENTRY)
    return block.arguments[0]


def _call(ctx, ctx_val, op, callee, arg_attrs):
    """Insert emitc.call_opaque <callee>(ctx) {args=[0:index, ...]} before `op`.
    The leading `0 : index` references operand 0 (ctx); other entries are
    literal C args (integer attr -> literal, #emitc.opaque -> verbatim)."""
    ir.Operation.create(
        "emitc.call_opaque", results=[], operands=[ctx_val],
        attributes={"callee": ir.StringAttr.get(callee),
                    "args": ir.ArrayAttr.get([_idx(0)] + arg_attrs)},
        loc=ir.Location.unknown(ctx), ip=ir.InsertionPoint(op))


def _innermost_outer_loop(block):
    """Deepest `affine.for {outer_loop=true}` (the PARALLEL/ACCUMULATION
    boundary). Returns the op or None if the kernel has no parallel loop."""
    found = [None]

    def is_outer(op):
        a = op.operation.attributes
        return "outer_loop" in a and ir.BoolAttr(a["outer_loop"]).value

    def walk(b):
        for op in b.operations:
            if op.operation.name == "affine.for" and is_outer(op):
                found[0] = op   # nested outer loops overwrite -> deepest wins
            for r in op.operation.regions:
                for bb in r.blocks:
                    walk(bb)

    walk(block)
    return found[0]


def _is_outer(forop):
    a = forop.operation.attributes
    return "outer_loop" in a and ir.BoolAttr(a["outer_loop"]).value


#: The role is carried by the `outer_loop` attribute, not the dialect:
#: PyTorchSim's codegen emits affine.for, _materialize_grid_loop scf.for. Both
#: keep the induction variable in block argument 0.
_LOOP_OPS = ("affine.for", "scf.for")
_LOOP_TERMINATORS = ("affine.yield", "scf.yield", "func.return")


def _parallel_loop_chain(block):
    """The nested chain of `{outer_loop}` loops from `block` inward (one
    work-item's parallel indices). Empty if the kernel has no parallel loop."""
    chain = []
    cur = block
    while True:
        nxt = None
        for op in cur.operations:
            if op.operation.name in _LOOP_OPS and _is_outer(op):
                nxt = op
                break
        if nxt is None:
            break
        chain.append(nxt)
        cur = nxt.operation.regions[0].blocks[0]
    return chain


def _const_op(value):
    """The defining arith/emitc constant Operation if `value` is a constant
    result, else None (block args / other ops)."""
    owner = value.owner
    if isinstance(owner, ir.Block):
        return None
    return owner if owner.name in ("arith.constant", "emitc.constant") else None


def _outline_work_item(ctx, kernel, ctx_val):
    """Outline the innermost parallel work-item body into a uniform
    `togsim_kernel_tile(ctx, iv, n)` func, replacing it with a
    `togsim_dispatch(ctx, togsim_kernel_tile, iv, n)` call (sec 9.3). The
    work-item SCOPE becomes the function body; the runtime wrapper owns the
    core-alloc + the TILE_BEGIN/TILE_END boundary (a decorator). One uniform tile
    signature -> a single general dispatcher serves every kernel.

    Runs after `_rewrite_togsim_ops`, so the moved body holds emitc.call_opaque
    (not togsim.* ops). The only values captured from outside the body are ctx,
    the enclosing parallel induction vars, and constants -- threaded via the iv
    array (parallel IVs) / cloned (constants); anything else is unsupported
    (dynamic shape -> P4)."""
    kblk = kernel.regions[0].blocks[0]
    chain = _parallel_loop_chain(kblk)
    if chain:
        L = chain[-1]
        Lbody = L.operation.regions[0].blocks[0]
        ivs = [c.operation.regions[0].blocks[0].arguments[0] for c in chain]
    else:                       # no parallel loop -> the whole kernel body is one work-item
        L = None
        Lbody = kblk
        ivs = []

    i64 = ir.IntegerType.get_signless(64)
    i32 = ir.IntegerType.get_signless(32)
    idxty = ir.IndexType.get()
    ctxty = ir.Type.parse(CTX_TYPE, ctx)
    i64ptr = ir.Type.parse("!emitc.ptr<i64>", ctx)
    loc = ir.Location.unknown(ctx)

    # --- the outlined tile function (before the kernel so C defines it first) ---
    tile = ir.Operation.create(
        "func.func", results=[], regions=1,
        attributes={
            "function_type": ir.TypeAttr.get(ir.FunctionType.get([ctxty, i64ptr, i32], [])),
            "sym_name": ir.StringAttr.get(ts.TILE_SYMBOL),
            "sym_visibility": ir.StringAttr.get("private")},
        loc=loc, ip=ir.InsertionPoint(kernel))
    with loc:
        tblk = tile.regions[0].blocks.append(ctxty, i64ptr, i32)
    ctx2, iv2, _n2 = tblk.arguments
    with ir.InsertionPoint(tblk):
        tret = ir.Operation.create("func.return", results=[], operands=[], loc=loc)

    # in the tile fn: recover each parallel index = index_cast(iv[k]).
    idx_vals = []
    with ir.InsertionPoint(tret):
        for k in range(len(ivs)):
            kc = ir.Operation.create("emitc.constant", results=[i64],
                    attributes={"value": ir.IntegerAttr.get(i64, k)}, loc=loc).results[0]
            ref = ir.Operation.create("emitc.subscript", results=[_lvalue(i64)],
                    operands=[iv2, kc], loc=loc).results[0]
            elem = ir.Operation.create("emitc.load", results=[i64],
                    operands=[ref], loc=loc).results[0]
            idx_vals.append(ir.Operation.create("arith.index_cast", results=[idxty],
                    operands=[elem], loc=loc).results[0])

    # move the work-item body into the tile fn (terminators stay behind).
    for op in [o for o in Lbody.operations
               if o.operation.name not in _LOOP_TERMINATORS]:
        op.operation.move_before(tret)

    # remap captures (Value `==` is identity): ctx -> ctx2, each parallel IV ->
    # its index_cast, each external constant -> a clone inside the tile fn. A
    # constant defined inside the tile fn (moved/read) is internal -> left alone.
    caps = [(ctx_val, ctx2)] + list(zip(ivs, idx_vals))
    internal_consts = []
    def _collect_internal(block):
        for op in block.operations:
            c = _const_op(op.operation.results[0]) if len(op.operation.results) == 1 else None
            if c is not None:
                internal_consts.append(op.operation.results[0])
            for rg in op.operation.regions:
                for b in rg.blocks:
                    _collect_internal(b)
    _collect_internal(tblk)
    const_clones = []
    ext_consts = []
    def _find_ext_consts(block):
        for op in block.operations:
            for opnd in op.operation.operands:
                if _const_op(opnd) is None:
                    continue
                if any(opnd == ic for ic in internal_consts):
                    continue
                if any(opnd == e for e in ext_consts):
                    continue
                ext_consts.append(opnd)
            for rg in op.operation.regions:
                for b in rg.blocks:
                    _find_ext_consts(b)
    _find_ext_consts(tblk)
    top = ir.InsertionPoint(tblk.operations[0])
    for e in ext_consts:
        c = _const_op(e)
        clone = ir.Operation.create(c.name, results=[e.type],
                    attributes={"value": c.attributes["value"]}, loc=loc, ip=top).results[0]
        const_clones.append((e, clone))

    allcaps = caps + const_clones
    def _remap(block):
        for op in block.operations:
            for i in range(len(op.operation.operands)):
                cur = op.operation.operands[i]
                for orig, new in allcaps:
                    if cur == orig:
                        op.operation.operands[i] = new
                        break
            for rg in op.operation.regions:
                for b in rg.blocks:
                    _remap(b)
    _remap(tblk)

    # --- the dispatcher: marshal the IVs and hand the tile fn to togsim_dispatch ---
    term = [o for o in Lbody.operations
            if o.operation.name in _LOOP_TERMINATORS][0]
    fn_ref = _opaque(ctx, ts.TILE_SYMBOL)   # function name -> verbatim pointer in C
    with ir.InsertionPoint(term):
        if ivs:
            arrty = ir.Type.parse("!emitc.array<%dxi64>" % len(ivs), ctx)
            arr = ir.Operation.create("emitc.variable", results=[arrty],
                    attributes={"value": _opaque(ctx, "")}, loc=loc).results[0]
            for k, iv in enumerate(ivs):
                kc = ir.Operation.create("emitc.constant", results=[i64],
                        attributes={"value": ir.IntegerAttr.get(i64, k)}, loc=loc).results[0]
                v64 = ir.Operation.create("arith.index_cast", results=[i64],
                        operands=[iv], loc=loc).results[0]
                sub = ir.Operation.create("emitc.subscript", results=[_lvalue(i64)],
                        operands=[arr, kc], loc=loc).results[0]
                # emitc.assign operands are (lvalue dest, value).
                ir.Operation.create("emitc.assign", results=[], operands=[sub, v64], loc=loc)
            ir.Operation.create(
                "emitc.call_opaque", results=[], operands=[ctx_val, arr],
                attributes={"callee": ir.StringAttr.get(ts.DISPATCH_CALLEE),
                            "args": ir.ArrayAttr.get(
                                [_idx(0), fn_ref, _idx(1), ir.IntegerAttr.get(i32, len(ivs))])},
                loc=loc)
        else:
            ir.Operation.create(
                "emitc.call_opaque", results=[], operands=[ctx_val],
                attributes={"callee": ir.StringAttr.get(ts.DISPATCH_CALLEE),
                            "args": ir.ArrayAttr.get(
                                [_idx(0), fn_ref, _opaque(ctx, "nullptr"), ir.IntegerAttr.get(i32, 0)])},
                loc=loc)


def _rewrite_togsim_ops(ctx, kernel, ctx_val):
    block = kernel.regions[0].blocks[0]
    victims = []
    for op in walk_ops(block):
        name = op.operation.name
        ipo = ir.InsertionPoint(op)
        if name == ts.DMA:
            dims = attr_i64_array(op, ts.ATTR_DIMS)
            # build_skeleton carries [dram_index, tag_index] (each optional) as
            # operands. Pass each as a call operand so convert-arith-to-emitc lowers
            # the address arithmetic into the producer; the runtime adds the base.
            ins = list(op.operation.operands)
            dram_operand = ins[0] if len(ins) >= 1 else None
            tag_operand = ins[1] if len(ins) >= 2 else None
            operands = [ctx_val]
            offset_arg = i64(0)
            tag_arg = i64(0)
            if dram_operand is not None:
                operands.append(dram_operand)
                offset_arg = _idx(len(operands) - 1)
            if tag_operand is not None:
                operands.append(tag_operand)
                tag_arg = _idx(len(operands) - 1)
            args = [_idx(0),
                    i32(attr_int(op, ts.ATTR_DIR)),
                    i32(attr_int(op, ts.ATTR_ARG_ID)),
                    offset_arg,
                    i32(len(dims)),
                    _arr(ctx, dims),
                    _arr(ctx, attr_i64_array(op, ts.ATTR_STRIDES)),
                    i32(attr_int(op, ts.ATTR_ELEM_BITS)),
                    i32(_attr_bool(op, ts.ATTR_IS_ASYNC)),
                    i32(attr_int(op, ts.ATTR_TAG_ID)),
                    tag_arg]
            _rb = attr_i64_array(op, ts.ATTR_READ_BUFS)
            _wb = attr_i64_array(op, ts.ATTR_WRITE_BUFS)
            args += [_arr(ctx, _rb), i32(len(_rb)), _arr(ctx, _wb), i32(len(_wb))]
            # togsim_dma is void: the dma is paired with its barrier by the runtime
            # (tag_id, tag_slot), not a returned handle.
            ir.Operation.create(
                "emitc.call_opaque", results=[], operands=operands,
                attributes={"callee": ir.StringAttr.get(ts.EMITC_CALLEE[ts.DMA]),
                            "args": ir.ArrayAttr.get(args)},
                loc=ir.Location.unknown(ctx), ip=ipo)
            victims.append(op)
        elif name == ts.MEMORY_BAR:
            # explicit async-DMA sync (the original dma_wait) ->
            # togsim_memory_barrier(ctx, tag_id, tag_slot, write_bufs). The tag
            # index operand (if any) is the runtime tag slot.
            ins = list(op.operation.operands)
            operands = [ctx_val]
            tag_arg = i64(0)
            if ins:
                operands.append(ins[0])
                tag_arg = _idx(len(operands) - 1)
            _wb = attr_i64_array(op, ts.ATTR_WRITE_BUFS)
            ir.Operation.create(
                "emitc.call_opaque", results=[], operands=operands,
                attributes={"callee": ir.StringAttr.get(ts.EMITC_CALLEE[ts.MEMORY_BAR]),
                            "args": ir.ArrayAttr.get(
                                [_idx(0), i32(attr_int(op, ts.ATTR_TAG_ID)), tag_arg,
                                 _arr(ctx, _wb), i32(len(_wb))])},
                loc=ir.Location.unknown(ctx), ip=ipo)
            victims.append(op)
        elif name == ts.COMPUTE:
            # skeleton compute carries no dims (cost is keyed by tile_id) -> 0/null.
            _rb = attr_i64_array(op, ts.ATTR_READ_BUFS)
            _wb = attr_i64_array(op, ts.ATTR_WRITE_BUFS)
            _call(ctx, ctx_val, op, ts.EMITC_CALLEE[ts.COMPUTE],
                  [i64(attr_int(op, ts.ATTR_TILE_ID)),
                   i32(attr_int(op, ts.ATTR_COMPUTE_TYPE)),
                   i32(0), _opaque(ctx, "nullptr"),
                   _arr(ctx, _rb), i32(len(_rb)), _arr(ctx, _wb), i32(len(_wb))])
            victims.append(op)
    for op in victims:
        op.operation.erase()


# ---------------------------------------------------------------------------
# step 3: post-conversion fixups
# ---------------------------------------------------------------------------
def _retype_for_to_size_t(module):
    """Make every `emitc.for` use `!emitc.size_t` bounds + induction variable,
    then drop the `index`<->`!emitc.size_t` `unrealized_conversion_cast` ops that
    `convert-scf-to-emitc` / `convert-arith-to-emitc` leave behind (mlir-to-cpp
    cannot print them; --reconcile cannot fold them).

    `emitc.for` accepts `size_t` bounds with the explicit type, and a `size_t` IV
    makes the lowered address arithmetic (`convert-arith-to-emitc`, which works
    in `size_t`) cast-free. So: set each IV to size_t, then for every
    index<->size_t cast replace its result with its source (every consumer here
    -- `emitc.for` bounds, `emitc.call_opaque` operands, `emitc` arith -- accepts
    either, and after the IV retype each such cast bridges equal types).

    The bounds settle only after the fold, so the induction variable is matched
    to them again at the end: a loop whose bounds are neither index nor size_t
    (Triton's own i32 reduction loop) keeps its own type, which `emitc.for`
    requires the induction variable to share."""
    idx = ir.IndexType.get()
    st = ir.Type.parse("!emitc.size_t", module.context)

    for op in list(walk_ops(module.body)):
        if op.operation.name == "emitc.for":
            op.operation.regions[0].blocks[0].arguments[0].set_type(st)

    dead = []
    for op in list(walk_ops(module.body)):
        if op.operation.name != "builtin.unrealized_conversion_cast":
            continue
        res = op.results[0]
        src = list(op.operation.operands)[0]
        # idx<->size_t bridges (incl. the size_t->size_t identities left after
        # the IV retype): every consumer here accepts either, so fold to source.
        if src.type in (idx, st) and res.type in (idx, st):
            res.replace_all_uses_with(src)
            dead.append(op)
    for d in dead:
        try:
            d.operation.erase()
        except Exception:
            pass

    for op in list(walk_ops(module.body)):
        if op.operation.name != "emitc.for":
            continue
        bounds = {v.type for v in list(op.operation.operands)[:3]}
        if len(bounds) == 1:
            op.operation.regions[0].blocks[0].arguments[0].set_type(bounds.pop())


def _add_extern_c(module, ctx):
    for op in module.body.operations:
        if (op.operation.name == "emitc.func"
                and ir.StringAttr(op.operation.attributes["sym_name"]).value == ENTRY):
            op.operation.attributes["specifiers"] = ir.ArrayAttr.get(
                [ir.StringAttr.get('extern "C"')])
            return
    raise ValueError("emitc.func @%s not found after conversion" % ENTRY)


# ---------------------------------------------------------------------------
# driver
# ---------------------------------------------------------------------------
#: Integer min/max, and the comparison that says the same thing. EmitC has no
#: form of its own for these; `arith.cmpi` and `arith.select` it does convert.
_INT_MINMAX = {"arith.minsi": "slt", "arith.maxsi": "sgt",
               "arith.minui": "ult", "arith.maxui": "ugt"}


def _expand_int_minmax(module):
    """`min(a, b)` -> `select(a < b, a, b)`, in place. Returns how many.

    WHY IT IS HERE AND NOT IN THE PIPELINE. `convert-arith-to-emitc` marks these
    four illegal and offers no pattern, and `arith-expand` only covers the ops
    that need extra arithmetic (ceildiv, floordiv, the float ones) -- an integer
    min needs none, so nothing upstream lowers it and the pipeline fails to
    legalize instead. There is no float case here: `arith.minimumf`/`maximumf`
    do have a conversion.

    WHERE IT COMES FROM. Inductor's mm and conv Triton templates bound the last
    tile with `min(M - pid * BLOCK_M, BLOCK_M)`. The kernel itself compiles and
    runs -- tnpu lowers the op fine and Spike writes the right values -- so this
    is the TIMING path only, which is why it surfaced as a working kernel whose
    trace producer would not build.
    """
    from mlir.dialects import arith
    # Collected first: walk_ops recurses into an op's regions AFTER yielding it,
    # so erasing during the walk invalidates the handle it is about to ask.
    victims = [(op, _INT_MINMAX[op.operation.name]) for op in walk_ops(module.body)
               if op.operation.name in _INT_MINMAX]
    done = 0
    for op, pred in victims:
        a, b = op.operation.operands
        with ir.InsertionPoint(op.operation), op.operation.location:
            # a<b picks a for a MIN and a>b picks a for a MAX, so the true arm
            # is `a` either way and only the predicate differs.
            cond = arith.CmpIOp(arith.CmpIPredicate[pred], a, b).result
            new = arith.SelectOp(cond, a, b).result
        _replace_all_uses(op.operation.results[0], new)
        op.operation.erase()
        done += 1
    return done


def lower_to_emitc(skeleton_module, work_item=None):
    """Lower a skeleton+API module (in place) to an EmitC module with the
    `togsim_kernel` entry function. Returns the same module.

    `work_item` is for kernels whose body is one work-item with the grid outside
    (Triton's shape); None keeps PyTorchSim's, where the tile loops are already
    in the kernel.
    """
    ctx = skeleton_module.context
    kernel = _find_kernel(skeleton_module)
    if kernel is None:
        raise ValueError("no kernel function found in skeleton module")

    _strip_aux(skeleton_module, keep=kernel)
    pending = []
    if work_item is not None:
        pending = _materialize_grid_loop(kernel, work_item, ctx)
    ctx_val = _rewrite_signature(kernel, ctx)
    _bind_runtime_bounds(pending, kernel.regions[0].blocks[0].arguments[1], ctx)
    _rewrite_togsim_ops(ctx, kernel, ctx_val)         # togsim.* -> emitc.call_opaque
    _outline_work_item(ctx, kernel, ctx_val)          # work-item body -> togsim_kernel_tile + dispatch
    _expand_int_minmax(skeleton_module)               # what convert-arith-to-emitc will not take

    PassManager.parse(_PIPELINE, ctx).run(skeleton_module.operation)

    _retype_for_to_size_t(skeleton_module)
    _add_extern_c(skeleton_module, ctx)
    return skeleton_module


# ---------------------------------------------------------------------------
# C++ / .so backend
# ---------------------------------------------------------------------------
def _mlir_translate_bin():
    return os.path.join(os.environ.get("TORCHSIM_LLVM_PATH", "/usr/bin"),
                        "mlir-translate")


def emitc_to_cpp(emitc_module, mlir_translate=None, include_dir=None):
    """Render `emitc_module` to C++ source (banner + includes + mlir-to-cpp body).
    `include_dir` locates togsim_runtime.h for the ABI banner (default resolves it)."""
    mlir_translate = mlir_translate or _mlir_translate_bin()
    proc = subprocess.run(
        [mlir_translate, "--mlir-to-cpp"],
        input=str(emitc_module), capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError("mlir-translate --mlir-to-cpp failed:\n" + proc.stderr)
    return _trace_banner(include_dir or _default_include_dir()) + _INCLUDES + proc.stdout


def compile_so(cpp_text, so_path, include_dir, cxx=None):
    """Compile producer C++ to `so_path`. `include_dir` must hold
    togsim_runtime.h. togsim_* symbols are left undefined (resolved at dlopen)."""
    cxx = cxx or os.environ.get("CXX", "g++")
    cpp_path = os.path.splitext(so_path)[0] + ".cpp"
    with open(cpp_path, "w") as fh:
        fh.write(cpp_text)
    proc = subprocess.run(
        [cxx, "-shared", "-fPIC", "-std=gnu++17", "-O2",
         "-I", include_dir, cpp_path, "-o", so_path],
        capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError("%s failed:\n%s" % (cxx, proc.stderr))
    return so_path


def _default_include_dir():
    root = os.environ.get("TORCHSIM_DIR")
    if not root:
        root = os.path.dirname(os.path.dirname(os.path.dirname(
            os.path.dirname(os.path.abspath(__file__)))))
    return os.path.join(root, "TOGSim", "include")


def skeleton_to_so(skeleton_module, so_path, include_dir=None, work_item=None):
    """skeleton module -> EmitC -> C++ -> compiled trace `.so`. Returns the
    EmitC module text (for inspection / caching)."""
    emitc = lower_to_emitc(skeleton_module, work_item=work_item)
    inc = include_dir or _default_include_dir()
    cpp = emitc_to_cpp(emitc, include_dir=inc)
    compile_so(cpp, so_path, inc)
    return str(emitc)


def build_trace_so(postvcix_path, so_path, include_dir=None, work_item=None):
    """Full P2 path from a post-vcix kernel .mlir to a trace `.so`.

    `work_item` -- see lower_to_emitc."""
    from . import build_skeleton as bs

    ctx = ir.Context()
    ctx.allow_unregistered_dialects = True
    with ctx:
        module = ir.Module.parse(open(postvcix_path).read(), ctx)
        bs.build_skeleton(module)
        return skeleton_to_so(module, so_path, include_dir, work_item=work_item)


def main(argv):
    import argparse

    parser = argparse.ArgumentParser(prog="lower_to_emitc.py")
    parser.add_argument("input", help="post-vcix kernel .mlir")
    parser.add_argument("--so", required=True, help="output .so path")
    parser.add_argument("--include-dir", default=None,
                        help="dir holding togsim_runtime.h (default: TOGSim/include)")
    parser.add_argument("--emit-cpp", default=None,
                        help="also write the generated C++ here")
    parser.add_argument("--emit-mlir", default=None,
                        help="also write the EmitC MLIR here")
    args = parser.parse_args(argv[1:])

    from . import build_skeleton as bs
    ctx = ir.Context()
    ctx.allow_unregistered_dialects = True
    with ctx:
        module = ir.Module.parse(open(args.input).read(), ctx)
        bs.build_skeleton(module)
        emitc = lower_to_emitc(module)
        if args.emit_mlir:
            open(args.emit_mlir, "w").write(str(emitc))
        cpp = emitc_to_cpp(emitc, include_dir=args.include_dir or _default_include_dir())
        if args.emit_cpp:
            open(args.emit_cpp, "w").write(cpp)
        compile_so(cpp, args.so, args.include_dir or _default_include_dir())
    import sys
    sys.stderr.write("wrote %s\n" % args.so)
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main(sys.argv))
