"""The simulator half of the TOGSim trace: gem5 cycles, and g++ on the
compiler's trace producer C++. Reads no MLIR.
"""

import os
import re
import subprocess

VECTOR_COMPUTE = 0
MATMUL_COMPUTE = 1
MATMUL_PRELOAD = 2


def overlapping_cycle(cycle, compute_type, x_offset, w_offset):
    """The pipeline-overlapped portion of cycle, by compute type."""
    if compute_type <= VECTOR_COMPUTE:
        return 0
    offset = w_offset if compute_type == MATMUL_PRELOAD else x_offset
    return max(int(cycle) - int(offset), 0)


def cycle_table(compute_types, cycle_list, x_offset, w_offset):
    """[(cycle, overlapping_cycle), ...] indexed by tile_id.

    compute_types comes from the compiler, cycle_list from gem5; both are in
    tile_id order.
    """
    if len(cycle_list) != len(compute_types):
        raise ValueError(
            f"gem5 returned {len(cycle_list)} cycle sample(s) for "
            f"{len(compute_types)} compute tile(s): a marker fired a different "
            f"number of times than there are tiles, so the table would be keyed "
            f"by the wrong samples")
    return [(int(c), overlapping_cycle(c, t, x_offset, w_offset))
            for c, t in zip(cycle_list, compute_types)]


def dump_cycle_table_tsv(table, path, origins=None):
    """cycle<TAB>overlapping per line, in tile_id order, for TOGSim's loader.

    origins is appended as a trailing comment line, which the loader stops at.
    """
    with open(path, "w") as fh:
        for cycle, overlapping in table:
            fh.write("%d\t%d\n" % (int(cycle), int(overlapping)))
        if origins:
            fh.write("# origins: %s\n" % ", ".join(sorted(str(o) for o in origins)))
    return path


def default_include_dir():
    """Where togsim_runtime.h lives."""
    root = os.environ.get("TORCHSIM_DIR")
    if not root:
        root = os.path.dirname(os.path.dirname(os.path.dirname(
            os.path.abspath(__file__))))
    return os.path.join(root, "TOGSim", "include")


def trace_banner(include_dir):
    """The trace.cpp header, with the ABI version read out of togsim_runtime.h.

    Falls back to a bare line when the header is unreadable.
    """
    head = "// GENERATED by PyTorchSim -- TOGSim trace producer. DO NOT EDIT.\n"
    try:
        text = open(os.path.join(include_dir, "togsim_runtime.h")).read()
    except OSError:
        return head
    ver = re.search(r"#define\s+TOGSIM_ABI_VERSION\s+(\d+)", text)
    blk = re.search(r"// --- BEGIN trace-producer call formats[^\n]*\n(.*?)"
                    r"// --- END trace-producer call formats[^\n]*\n", text, re.S)
    head = ("// GENERATED by PyTorchSim -- TOGSim trace producer (ABI v%s). DO NOT EDIT.\n"
            % (ver.group(1) if ver else "?"))
    return head + (blk.group(1) if blk else "")


def compile_so(cpp_text, so_path, include_dir, cxx=None):
    """Compile the producer C++ to so_path, leaving togsim_* undefined.

    include_dir must hold togsim_runtime.h.
    """
    cxx = cxx or os.environ.get("CXX", "g++")
    cpp_path = os.path.splitext(so_path)[0] + ".cpp"
    with open(cpp_path, "w") as fh:
        fh.write(cpp_text)
    proc = subprocess.run(
        [cxx, "-shared", "-fPIC", "-std=gnu++17", "-O2",
         "-I", include_dir, cpp_path, "-o", so_path],
        capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError("%s failed:\n%s" % (cxx, proc.stderr))
    return so_path
