"""The simulator's half of the TOGSim trace: cycles measured here, C++ compiled here.

The compiler emits the trace producer as C++ (`trace_cpp`) and the compute type
of every tile (`tile_types`); it reads the IR it printed itself and stops there.
What is left is everything that needs a simulator:

    trace_banner        the ABI comment, read out of TOGSim's own header
    compile_so          g++ -I TOGSim/include -> trace.so
    cycle_table         gem5's per-tile cycles + those types -> the table
    dump_cycle_table_tsv    the format TOGSim's --cycle_table loader reads

WHY THE LINE IS HERE. The two repositories used to exchange MLIR TEXT, which is
not stable across LLVM revisions, so both had to hold the same LLVM and this one
carried gigabytes of one to parse IR the other had just printed. Nothing in this
file reads MLIR. What it does read is togsim_runtime.h, which is TOGSim's own
and sits beside it -- a compiler that opened that header would have turned the
seam around rather than removed it.
"""

import os
import re
import subprocess

#: Compute types, mirroring TileOperationGraph.h. The compiler stamps one on
#: every tile and passes them through tile_types.json; the formula below is the
#: only reason this side needs to know what they mean.
VECTOR_COMPUTE = 0
MATMUL_COMPUTE = 1
MATMUL_PRELOAD = 2


def overlapping_cycle(cycle, compute_type, x_offset, w_offset):
    """The pipeline-overlapped portion of `cycle`.

    Mirrors tog_generator.generate_tile_graph, which the timing core consumes as
    `finish = prev.finish + cycle - overlapped` (Core.cc):

        VectorCompute   -> 0, there is no systolic array to overlap with
        MatmulCompute   -> max(cycle - x_offset, 0)
        MatmulPreload   -> max(cycle - w_offset, 0)
    """
    if compute_type <= VECTOR_COMPUTE:
        return 0
    offset = w_offset if compute_type == MATMUL_PRELOAD else x_offset
    return max(int(cycle) - int(offset), 0)


def cycle_table(compute_types, cycle_list, x_offset, w_offset):
    """`[(cycle, overlapping_cycle), ...]` indexed by tile_id.

    `compute_types` comes from the compiler's tile_types.json and `cycle_list`
    from gem5, and the two are in the same order because both are keyed by
    tile_id -- which is build_skeleton's compute-node order, the same order the
    sample-mode markers fire in.
    """
    if len(cycle_list) != len(compute_types):
        raise ValueError(
            f"gem5 returned {len(cycle_list)} cycle sample(s) for "
            f"{len(compute_types)} compute tile(s): a marker fired a different "
            f"number of times than there are tiles, so the table would be keyed "
            f"by the wrong samples")
    return [(int(c), overlapping_cycle(c, t, x_offset, w_offset))
            for c, t in zip(cycle_list, compute_types)]


def dump_cycle_table_tsv(table, path, origins=None):
    """`cycle<TAB>overlapping` per line, in tile_id order.

    The trivial format TOGSim's `--cycle_table` loader reads with an ifstream
    (main.cc) -- no JSON dependency on that side. `origins` (the FX nodes this
    kernel came from) is recorded as a trailing `# origins:` comment; the
    loader's `while (ct >> c >> o)` stops at the `#` once the rows are read, so
    it is safe with the current parser.
    """
    with open(path, "w") as fh:
        for cycle, overlapping in table:
            fh.write("%d\t%d\n" % (int(cycle), int(overlapping)))
        if origins:
            fh.write("# origins: %s\n" % ", ".join(sorted(str(o) for o in origins)))
    return path


def default_include_dir():
    """Where togsim_runtime.h lives."""
    root = os.environ.get("TORCHSIM_DIR")
    if not root:
        root = os.path.dirname(os.path.dirname(os.path.dirname(
            os.path.abspath(__file__))))
    return os.path.join(root, "TOGSim", "include")


def trace_banner(include_dir):
    """The generated trace.cpp's self-documenting header.

    The ABI version and the call-format block are READ OUT of togsim_runtime.h
    so they cannot drift when the ABI changes. This is why the banner is added
    HERE and not by the compiler: it is a fact about the simulator, and the
    compiler does not get to depend on the simulator it targets. Falls back to a
    bare line when the header is unreadable.
    """
    head = "// GENERATED by PyTorchSim -- TOGSim trace producer. DO NOT EDIT.\n"
    try:
        text = open(os.path.join(include_dir, "togsim_runtime.h")).read()
    except OSError:
        return head
    ver = re.search(r"#define\s+TOGSIM_ABI_VERSION\s+(\d+)", text)
    blk = re.search(r"// --- BEGIN trace-producer call formats[^\n]*\n(.*?)"
                    r"// --- END trace-producer call formats[^\n]*\n", text, re.S)
    head = ("// GENERATED by PyTorchSim -- TOGSim trace producer (ABI v%s). DO NOT EDIT.\n"
            % (ver.group(1) if ver else "?"))
    return head + (blk.group(1) if blk else "")


def compile_so(cpp_text, so_path, include_dir, cxx=None):
    """Compile the producer C++ to `so_path`.

    `include_dir` must hold togsim_runtime.h. The `togsim_*` symbols are left
    undefined on purpose -- TOGSim resolves them when it dlopens the result.
    """
    cxx = cxx or os.environ.get("CXX", "g++")
    cpp_path = os.path.splitext(so_path)[0] + ".cpp"
    with open(cpp_path, "w") as fh:
        fh.write(cpp_text)
    proc = subprocess.run(
        [cxx, "-shared", "-fPIC", "-std=gnu++17", "-O2",
         "-I", include_dir, cpp_path, "-o", so_path],
        capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError("%s failed:\n%s" % (cxx, proc.stderr))
    return so_path
